# Generated by Django 3.1.2 on 2024-05-13 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagenProducto',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
