# Generated by Django 3.1.2 on 2024-05-10 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20240509_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariocustom',
            name='idComuna',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.comuna'),
        ),
        migrations.AlterField(
            model_name='usuariocustom',
            name='idRol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.rolusuario'),
        ),
    ]
