# Generated by Django 3.1.2 on 2024-05-10 02:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20240509_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariocustom',
            name='fecha_nacimiento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='usuariocustom',
            name='idComuna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.comuna'),
        ),
        migrations.AlterField(
            model_name='usuariocustom',
            name='idRol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.rolusuario'),            preserve_default=False,
        ),
    ]
