# Generated by Django 3.1.2 on 2024-05-10 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20240509_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariocustom',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
