# Generated by Django 3.1.2 on 2024-05-22 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20240517_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descripcionProducto',
            field=models.CharField(max_length=400),
        ),
    ]
