# Generated by Django 3.1.2 on 2024-05-11 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20240509_2243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariocustom',
            name='idComuna',
        ),
        migrations.RemoveField(
            model_name='usuariocustom',
            name='idRol',
        ),
    ]
