# Generated by Django 3.1.2 on 2024-05-11 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20240511_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariocustom',
            name='idComuna',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.comuna'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuariocustom',
            name='idRol',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='core.rolusuario'),
            preserve_default=False,
        ),
    ]
