# Generated by Django 3.1.2 on 2024-05-22 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20240522_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='apellido',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='comuna',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.comuna'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='direccion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='nombre',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.region'),
            preserve_default=False,
        ),
    ]
