# Generated by Django 3.1.2 on 2024-05-26 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20240522_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.sucursal'),
        ),
    ]
