# Generated by Django 3.1.2 on 2024-05-26 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_pedido_sucursal'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='run',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
