# Generated by Django 3.1.2 on 2024-05-26 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_pedido_run'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='comuna',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.comuna'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.region'),
        ),
    ]
