# Generated by Django 3.1.2 on 2024-05-26 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20240526_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='apellido_retiro',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='nombre_retiro',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
