# Generated by Django 3.1.2 on 2024-05-26 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20240526_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='tipo_entrega',
            field=models.CharField(choices=[('envio_domicilio', 'Envío a domicilio'), ('retiro_tienda', 'Retiro en tienda')], default='Retiro en tienda', max_length=20),
            preserve_default=False,
        ),
    ]
