# Generated by Django 3.1.2 on 2024-05-26 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_pedido_tipo_entrega'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariocustom',
            name='correo_usuario',
        ),
    ]
