# Generated by Django 3.1.2 on 2024-05-26 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_usuariocustom_correo_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariocustom',
            name='correo_usuario',
            field=models.EmailField(default='ferremas@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
