# Generated by Django 3.1.2 on 2024-05-05 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_usuariocustom_fecha_nacimiento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuariocustom',
            old_name='dirrecion',
            new_name='direccion',
        ),
    ]
