# Generated by Django 3.1.2 on 2024-05-06 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_auto_20240505_2124'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuariocustom',
            managers=[
            ],
        ),
    ]
