# Generated by Django 3.1.2 on 2024-05-06 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_auto_20240506_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariocustom',
            name='fecha_nacimiento',
            field=models.DateField(null=True),
        ),
    ]
