# Generated by Django 3.1.2 on 2024-05-07 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0007_auto_20240506_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariocustom',
            name='fecha_nacimiento',
            field=models.DateField(null=True),
        ),
    ]
